version: '3'

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD=postgres
            POSTGRES_USER=postgres
            POSTGRES_DB=postgres

    backend:
        build: .
        ports:
            - "8000:8000"
        environment:
            POSTGRES_PASSWORD=postgres
            POSTGRES_USER=postgres
            POSTGRES_DB=postgres
        volumes:
            - .:/app
        depends_on:
            - db
    
    frontend:
        build: ./application_tracker/static/application_tracker/frontend
        volumes: ./application_tracker/static/application_tracker/frontend:/
        depends_on:
            - backend